// contains the Puppies component that will display the list of puppies fetched from the backend API
// contains the form to add, delete, and update puppies

import { useEffect, useState } from 'react';
import axios from 'axios';

// create an axios instance with the base URL from the environment variable
const api = axios.create({ baseURL: import.meta.env.VITE_API_BASE_URL });

// Puppies table app with CRUD operations
const Body = () => {
  const [puppies, setPuppies] = useState([]);
  const [form, setForm] = useState({
    id: '',
    name: '',
    breed: '',
    age: '',
    user_id: '',
  });

  // fetch all puppies 
  const load = async () => {
    try {
      console.log('Base URL:', import.meta.env.VITE_API_BASE_URL);
      const res = await api.get('/puppies');
      console.log('Puppies response:', res.data);
      setPuppies(Array.isArray(res.data) ? res.data : []);
    } catch (error) {
      console.error('Failed to load puppies:', error.response?.data || error.message);
    }
  };

  // load puppies on initial render
  useEffect(() => {
    load();
  }, []);

  // handle form input changes
  const onChange = (e) =>
    setForm((f) => ({ ...f, [e.target.name]: e.target.value }));

  // reset form after add, delete, or update
  const resetForm = () => {
    setForm({
      id: '',
      name: '',
      breed: '',
      age: '',
      user_id: '',
    });
  };

  // add puppy
  const onSubmit = async (e) => {
    e.preventDefault();

    try {
      await api.post('/puppies', {
        // send the puppy fields to create a new puppy
        // id is not needed here because it is auto-generated by the database
        name: form.name,
        breed: form.breed,
        age: form.age
      });

      resetForm();
      await load();
    } catch (error) {
      console.error('Failed to add puppy:', error.response?.data || error.message);
      alert('Failed to add puppy. Please check the form and try again.');
    }
  };

  // delete puppy by id - needed to add better error handling
  const onDelete = async (e) => {
    e.preventDefault();

    try {
      // attempt to delete the puppy based on id
      await api.delete(`/puppies/${form.id}`);

      // if successful, reset form and reload puppy list
      resetForm();
      await load();
    } catch (error) {
      // log error
      console.error('Failed to delete puppy:', error.response?.data || error.message);
      // alert user
      alert('Failed to delete puppy. Please check the ID and try again.');
    }
  };

  // update puppy by id
  const onUpdate = async (e) => {
    e.preventDefault();

    try {
      await api.put(`/puppies/${form.id}`, {
        // send only the fields that belong in the request body
        // id should stay in the URL, not inside the updated data
        name: form.name,
        breed: form.breed,
        age: form.age,
        user_id: form.user_id || null
      });

      resetForm();
      await load();
    } catch (error) {
      console.error('Failed to update puppy:', error.response?.data || error.message);
      alert('Failed to update puppy. Please make sure all required fields are filled in.');
    }
  };

  return (
    // create the main table with data from the puppies database 
    <main className="app-main">
      <section className="data-section">
        <div className="table-container">
          <table>
            <thead>
              <tr>
                <th>Puppy ID</th>
                <th>Name</th>
                <th>Breed</th>
                <th>Age</th>
                <th>User ID</th>
              </tr>
            </thead>
            <tbody>
              {puppies.map(pup => (
                <tr key={pup.id}>
                  <td>{pup.id}</td>
                  <td>{pup.name}</td>
                  <td>{pup.breed}</td>
                  <td>{pup.age}</td>
                  <td>{pup.user_id}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>

      <section className="forms-section">
        <div className="forms-grid">
          <div className="form-card">
            <h3>Add New Puppy</h3>
            <form onSubmit={onSubmit}>
              <div className="form-group">
                <input name="name" value={form.name} onChange={onChange} placeholder="Puppy Name" required />
              </div>
              <div className="form-group">
                <input name="breed" value={form.breed} onChange={onChange} placeholder="Breed" required />
              </div>
              <div className="form-group">
                <input name="age" value={form.age} onChange={onChange} placeholder="Age" required />
              </div>
              <button type="submit" className="btn-primary">Add Puppy</button>
            </form>
          </div>

          <div className="form-card">
            <h3>Delete Puppy</h3>
            <form onSubmit={onDelete}>
              <div className="form-group">
                <input name="id" value={form.id} onChange={onChange} placeholder="PuppyID to delete" required />
              </div>
              <button type="submit" className="btn-danger">Delete Puppy</button>
            </form>
          </div>

          <div className="form-card">
            <h3>Update Puppy</h3>
            <form onSubmit={onUpdate}>
              <div className="form-group">
                <input name="id" value={form.id} onChange={onChange} placeholder="Puppy ID to update" required />
              </div>
              <div className="form-group">
                <input name="name" value={form.name} onChange={onChange} placeholder="Name" />
              </div>
              <div className="form-group">
                <input name="breed" value={form.breed} onChange={onChange} placeholder="Breed" />
              </div>
              <div className="form-group">
                <input name="age" value={form.age} onChange={onChange} placeholder="Age"/>
              </div>
              <button type="submit" className="btn-secondary">Update Puppy</button>
            </form>
          </div>
        </div>
      </section>
    </main>
  );
}

export default Body;